### PR TITLE
Revert "Wrote new classes NewsConn, DerivConn, DerivativeInfo, new examples.py and more"

### PR DESCRIPTION
**Pull request by akapur**
Reverts akapur/pyiqfeed#5

Sorry had to revert this merge.

The NewsConn class is great new functionality.
The DerivConn class is great new functionality but see below.

Here is what's not so great:

1) Could you please make the code comply with PEP8.
2) Could you please run the code through a static code checker. There are a few available and all are free. I'm seeing a bunch of obvious errors like "a == None" instead of "a is None".
3) The DerivConn class should really be named BarConn or some such. This is a connection which receives real-time data that is derived from tick-data. Right now the only derived data is bars. You wouldn't use this for historical bars since the HistoryConn does that already.
4) The DerivInfo class shouldn't be in conn.py. It should really be in a new file called symbology.py or some such. This is parsing the symbol for a Derivative Security (option, future) etc.
5) The DerivInfo and DerivConn class should have no dependencies between them. You can use the DerivConn class (should be renamed to BarConn) for getting real-time bars of a stock if you want that. Fix the design.
6) The fix to the pydoc issues is to add exceptions to **init**.py. I don't think you need the huge kludge to make pydoc work. I added it to my code and on a ubuntu box, mac and windows it works.
7) You changed how mkt_time is read and the comment says it's a hard to find bug in Linux. You basically don't parse the field if it's blank. However, in a reverted version of the code, I had an assertion that checks that the field is not blank and I can't get the assertion to trigger on Windows, Linux or a Mac. Could you please enable verbose logging and look at the logs to see precisely what is going across the wire when you get this hard to find bug. I suspect the bug may be elsewhere as opposed to something from DTN on Linux.

### CODE REVIEW

**Comment by erickmiller** [comment]
Found the comments :)  I'll get on to making the updates.  Here's my response:

Comments 1 and 2 cool, yes, I can do that - probably should have already I'm pretty sure a== None is not an error (at least not a logical error) in that context as a is explicitly set to None earlier but it may not be Pep compliant.   If we are going to get PEP compliant you might want to look into converting tabs to whitespace characters also, PyCharm went nuts when I opened the files all kind of Pep errors but I'll look at fixing that stuff too while I do this part.

Comment 3, yes your name suggestion makes more sense - I called it Deriv because iqfeed refers to this command specifically for Derivatives in the documentation and I didn't test it with anything but derivatives, i.e. in the Derivatives section:  http://www.iqfeed.net/dev/api/docs/Derivatives_Overview.cfm
If this command works for symbols other than derivatives than I agree with your comments.  I just tested it and it appears after a few tweaks to my code that this will work with more than just derivatives despite being called out as for derivatives by iqfeed, so I'll look into the name

Comment 4: cool with moving this into it's own file, i think this class to be part of this library makes less sense now though since DerivConn is not just for derivatives I will rename it to BarConn and remove DerivativeInfo from the project, feel free to use that code in future if you'd like.

Comment 5: Yes I didn't realize this, thanks for pointing out -- I just tweaked the code so there is no longer a dependency to DerivativeInfo.  Feel free to use it in a future branch if it's useful but removing from this lib as it makes less sense when considering that API call works for more than just derivatives (despite confusion from iqfeed docs).

Comment 6 yeah agree removing this is cleaner and that solution is kind of kludgy but relative imports no longer work the same in 3.5 and didn't find another quick solution since it's a path related issue.   I would like to have quick docs that doesn't include browsing source code each time, would be awesome to have some more doc strings in the main calls also -- did you get pydoc to work?   What command did you use?  I tried running on module and on individual files both failed.   

Comment 7 - you may be correct this is probably not a linux related issue, i mentioned this because that is the platform I've coded and tested on, probably should have worded the comment more clearly.  It was a bug I was running into when iqfeed wasn't connecting fully.  I spent about 30 minutes debugging this and it was both intermittent and even after tracing through all the various other functions, was not clear as to the cause other than it looked like DTN was not returning a field in this case which in the times it happened caused exceptions (maybe an exception is the right thing to do here but since it appeared to be coming from DTN this way and it wasn't a DTN error code, it didn't seem like something to throw an exception on) I think this was related to the connection code, like if the UI for iqfeed proxy didn't start up fast enough (before / while I was adding the new code for the posix conditional to service.py).   Not sure though and did spend a decent amount of time looking to resolve this.  I'll look at changing or removing this and see if the error comes back.  Any further ideas?

**Comment by akapur** [comment]
Regarding 6, if adding the word exceptions to the list at the top of **init**.py does not fix the problem for you, then the simple solution unless we at some point end up needing a collection of exceptions (unlikely) in the project is to just move the definition of NoDataError to conn.py. It's just two lines of code and drop the file exceptions.py for now. I don't necessarily think we are going to need a hierarchy of exceptions in this project and we can probably even remove the class NoDataError altogether with a bit more work.

**Comment by erickmiller** [comment]
Cool, after adding exceptions to **init** I also was able to get pydoc to generate docs at the module level using:
pydoc3.5 pyiqfeed.conn

I agree it could be removed in fact I actually did that locally during testing and reverted my changes.  At any rate it seems to work now so this is probably sufficient.  

Also ran all the code through autopep and pylint for PEP compliance.  No errors except some unrelated numpy errors (sent in you an email w/ them)

Made all other requested changes as commented and will commit and send pull request shortly.

**Comment by erickmiller** [comment]
Cool, just sent pull request here: https://github.com/akapur/pyiqfeed/pull/8/

It seems there are conflicts... didn't expect that, it's almost certainly because of the pep compliance, feel free to check conflict markers and just resolve or ask me any questions if there is any real logic collision (which I don't think there is).

**Pull request merged**
